### ISSUE TITLE
[EPIC] : Re-organize content for the meetups

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/operate-first-data-science-community#67]
We would want to push all the content from the past and the upcoming meetups to the Opf Website. This is a proposed structure that we could follow to have organized content for all the meetups.

- [ ] A blog post that would contain links to the video and the presentation slides ( #50 )
- [ ] A folder in `docs/content` for each meetup with respective blogs and slides (#54 collected all the slides, reorganize these once all blogs are also ready )
- [ ] Updates in the agenda - `content.md` with all the three content items - blog, video link and slides
